# Generated by Django 4.2.4 on 2023-08-30 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificate_app', '0003_certificate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=100)),
                ('death_date', models.DateField()),
                ('death_location', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('image', models.FileField(upload_to='img')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('evidence_of_death', models.FileField(null=True, upload_to='docs')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
